image: gitpod/workspace-full

tasks:
  - name: Install Hacking Tools
    init: |
      echo "🚀 Installing Nuclei, SQLmap, Dalfox..."
      
      # Install Nuclei
      sudo apt update && sudo apt install -y golang git
      go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
      nuclei -update-templates

      # Install SQLmap
      pip3 install sqlmap

      # Install Dalfox (XSS)
      go install github.com/dproject/dalfox@latest

      # Install Recon Tools
      go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
      go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

      echo "✅ All tools installed. Happy hunting."

    command: echo "💡 Run 'nuclei -h' or 'sqlmap -h' to start scanning."

vscode:
  extensions:
    - ms-python.python
    - github.copilot
