image: gitpod/workspace-full

tasks:
  - name: Immunefi Auto Scanner
    init: |
      echo "🧨 Building Immunefi Auto Scanner..."
      sudo apt update && sudo apt install -y python3-pip solc
      pip3 install slither-analyzer mythril echidna
      pip3 install -r requirements.txt
    command: |
      echo "✅ Scanner ready. Run: ./run.sh"

vscode:
  extensions:
    - ms-python.python
    - ms-vscode.vscode-json
